/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Thu Feb 21 13:45:12 2019. */

#include "BatchOperationsMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TextLayerPropsMessage_fields[13] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, TextLayerPropsMessage, alignment, alignment, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, height, alignment, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, left, height, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, text, left, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, top, text, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, width, top, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, alignmentChanged, width, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, heightChanged, alignmentChanged, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, leftChanged, heightChanged, 0),
    PB_FIELD( 10, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, textChanged, leftChanged, 0),
    PB_FIELD( 11, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, topChanged, textChanged, 0),
    PB_FIELD( 12, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, widthChanged, topChanged, 0),
    PB_LAST_FIELD
};

const pb_field_t OperationMessage_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, OperationMessage, operation, operation, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, OperationMessage, nodeType, operation, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, OperationMessage, nodeId, nodeType, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, OperationMessage, textLayerProps, nodeId, &TextLayerPropsMessage_fields),
    PB_LAST_FIELD
};

const pb_field_t BatchOperationsMessage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, BatchOperationsMessage, operations, operations, &OperationMessage_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(OperationMessage, textLayerProps) < 65536 && pb_membersize(BatchOperationsMessage, operations[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_TextLayerPropsMessage_OperationMessage_BatchOperationsMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(OperationMessage, textLayerProps) < 256 && pb_membersize(BatchOperationsMessage, operations[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_TextLayerPropsMessage_OperationMessage_BatchOperationsMessage)
#endif


/* @@protoc_insertion_point(eof) */
