/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sun Feb 24 00:19:02 2019. */

#include "BatchOperationsMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TextLayerPropsMessage_fields[13] = {
    PB_FIELD(  1, STRING  , SINGULAR, POINTER , FIRST, TextLayerPropsMessage, alignment, alignment, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, height, alignment, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, left, height, 0),
    PB_FIELD(  4, STRING  , SINGULAR, POINTER , OTHER, TextLayerPropsMessage, text, left, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, top, text, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, width, top, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, alignmentChanged, width, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, heightChanged, alignmentChanged, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, leftChanged, heightChanged, 0),
    PB_FIELD( 10, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, textChanged, leftChanged, 0),
    PB_FIELD( 11, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, topChanged, textChanged, 0),
    PB_FIELD( 12, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, widthChanged, topChanged, 0),
    PB_LAST_FIELD
};

const pb_field_t AnimationPropsMessage_fields[11] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, AnimationPropsMessage, loop, loop, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, sequence, loop, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, POINTER , OTHER, AnimationPropsMessage, endOperations, sequence, &OperationMessage_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, POINTER , OTHER, AnimationPropsMessage, startOperations, endOperations, &OperationMessage_fields),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, delay, startOperations, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, duration, delay, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, durationChanged, duration, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, delayChanged, durationChanged, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, loopChanged, delayChanged, 0),
    PB_FIELD( 10, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, sequenceChanged, loopChanged, 0),
    PB_LAST_FIELD
};

const pb_field_t OperationMessage_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, OperationMessage, operation, operation, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, OperationMessage, nodeType, operation, 0),
    PB_FIELD(  3, STRING  , SINGULAR, POINTER , OTHER, OperationMessage, nodeId, nodeType, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, POINTER , OTHER, OperationMessage, textLayerProps, nodeId, &TextLayerPropsMessage_fields),
    PB_FIELD(  5, MESSAGE , SINGULAR, POINTER , OTHER, OperationMessage, animationProps, textLayerProps, &AnimationPropsMessage_fields),
    PB_LAST_FIELD
};

const pb_field_t BatchOperationsMessage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, POINTER , FIRST, BatchOperationsMessage, operations, operations, &OperationMessage_fields),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
