/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Tue Mar  5 12:06:41 2019. */

#include "BatchOperationsMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t LayerPropsMessage_fields[9] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, LayerPropsMessage, height, height, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, LayerPropsMessage, left, height, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, LayerPropsMessage, top, left, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, LayerPropsMessage, width, top, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, LayerPropsMessage, heightChanged, width, 0),
    PB_FIELD(  6, BOOL    , SINGULAR, STATIC  , OTHER, LayerPropsMessage, leftChanged, heightChanged, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, LayerPropsMessage, topChanged, leftChanged, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, LayerPropsMessage, widthChanged, topChanged, 0),
    PB_LAST_FIELD
};

const pb_field_t TextLayerPropsMessage_fields[7] = {
    PB_FIELD(  1, STRING  , SINGULAR, POINTER , FIRST, TextLayerPropsMessage, alignment, alignment, 0),
    PB_FIELD(  2, STRING  , SINGULAR, POINTER , OTHER, TextLayerPropsMessage, text, alignment, 0),
    PB_FIELD(  3, MESSAGE , SINGULAR, POINTER , OTHER, TextLayerPropsMessage, layerProps, text, &LayerPropsMessage_fields),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, alignmentChanged, layerProps, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, textChanged, alignmentChanged, 0),
    PB_FIELD(  6, BOOL    , SINGULAR, STATIC  , OTHER, TextLayerPropsMessage, layerPropsChanged, textChanged, 0),
    PB_LAST_FIELD
};

const pb_field_t CircleLayerPropsMessage_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, CircleLayerPropsMessage, radius, radius, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, POINTER , OTHER, CircleLayerPropsMessage, layerProps, radius, &LayerPropsMessage_fields),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, CircleLayerPropsMessage, radiusChanged, layerProps, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, CircleLayerPropsMessage, layerPropsChanged, radiusChanged, 0),
    PB_LAST_FIELD
};

const pb_field_t AnimationPropsMessage_fields[11] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, AnimationPropsMessage, loop, loop, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, sequence, loop, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, POINTER , OTHER, AnimationPropsMessage, endOperations, sequence, &OperationMessage_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, POINTER , OTHER, AnimationPropsMessage, startOperations, endOperations, &OperationMessage_fields),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, delay, startOperations, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, duration, delay, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, durationChanged, duration, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, delayChanged, durationChanged, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, loopChanged, delayChanged, 0),
    PB_FIELD( 10, BOOL    , SINGULAR, STATIC  , OTHER, AnimationPropsMessage, sequenceChanged, loopChanged, 0),
    PB_LAST_FIELD
};

const pb_field_t OperationMessage_fields[9] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, OperationMessage, operation, operation, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, OperationMessage, nodeType, operation, 0),
    PB_FIELD(  3, STRING  , SINGULAR, POINTER , OTHER, OperationMessage, nodeId, nodeType, 0),
    PB_FIELD(  4, STRING  , SINGULAR, POINTER , OTHER, OperationMessage, parentNodeId, nodeId, 0),
    PB_FIELD(  5, MESSAGE , SINGULAR, POINTER , OTHER, OperationMessage, textLayerProps, parentNodeId, &TextLayerPropsMessage_fields),
    PB_FIELD(  6, MESSAGE , SINGULAR, POINTER , OTHER, OperationMessage, animationProps, textLayerProps, &AnimationPropsMessage_fields),
    PB_FIELD(  7, MESSAGE , SINGULAR, POINTER , OTHER, OperationMessage, layerProps, animationProps, &LayerPropsMessage_fields),
    PB_FIELD(  8, MESSAGE , SINGULAR, POINTER , OTHER, OperationMessage, circleLayerProps, layerProps, &CircleLayerPropsMessage_fields),
    PB_LAST_FIELD
};

const pb_field_t BatchOperationsMessage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, POINTER , FIRST, BatchOperationsMessage, operations, operations, &OperationMessage_fields),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
