# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/brunobasto/Projects/pebble/pbl-react/packages/pebble-react

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/brunobasto/Projects/pebble/pbl-react/packages/pebble-react

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brunobasto/Projects/pebble/pbl-react/packages/pebble-react/CMakeFiles /Users/brunobasto/Projects/pebble/pbl-react/packages/pebble-react/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brunobasto/Projects/pebble/pbl-react/packages/pebble-react/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PebbleReact

# Build rule for target.
PebbleReact: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PebbleReact
.PHONY : PebbleReact

# fast build rule for target.
PebbleReact/fast:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/build
.PHONY : PebbleReact/fast

src/c/reconcilers/animation.o: src/c/reconcilers/animation.c.o

.PHONY : src/c/reconcilers/animation.o

# target to build an object file
src/c/reconcilers/animation.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/animation.c.o
.PHONY : src/c/reconcilers/animation.c.o

src/c/reconcilers/animation.i: src/c/reconcilers/animation.c.i

.PHONY : src/c/reconcilers/animation.i

# target to preprocess a source file
src/c/reconcilers/animation.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/animation.c.i
.PHONY : src/c/reconcilers/animation.c.i

src/c/reconcilers/animation.s: src/c/reconcilers/animation.c.s

.PHONY : src/c/reconcilers/animation.s

# target to generate assembly for a file
src/c/reconcilers/animation.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/animation.c.s
.PHONY : src/c/reconcilers/animation.c.s

src/c/reconcilers/arc_layer.o: src/c/reconcilers/arc_layer.c.o

.PHONY : src/c/reconcilers/arc_layer.o

# target to build an object file
src/c/reconcilers/arc_layer.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/arc_layer.c.o
.PHONY : src/c/reconcilers/arc_layer.c.o

src/c/reconcilers/arc_layer.i: src/c/reconcilers/arc_layer.c.i

.PHONY : src/c/reconcilers/arc_layer.i

# target to preprocess a source file
src/c/reconcilers/arc_layer.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/arc_layer.c.i
.PHONY : src/c/reconcilers/arc_layer.c.i

src/c/reconcilers/arc_layer.s: src/c/reconcilers/arc_layer.c.s

.PHONY : src/c/reconcilers/arc_layer.s

# target to generate assembly for a file
src/c/reconcilers/arc_layer.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/arc_layer.c.s
.PHONY : src/c/reconcilers/arc_layer.c.s

src/c/reconcilers/circle_layer.o: src/c/reconcilers/circle_layer.c.o

.PHONY : src/c/reconcilers/circle_layer.o

# target to build an object file
src/c/reconcilers/circle_layer.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/circle_layer.c.o
.PHONY : src/c/reconcilers/circle_layer.c.o

src/c/reconcilers/circle_layer.i: src/c/reconcilers/circle_layer.c.i

.PHONY : src/c/reconcilers/circle_layer.i

# target to preprocess a source file
src/c/reconcilers/circle_layer.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/circle_layer.c.i
.PHONY : src/c/reconcilers/circle_layer.c.i

src/c/reconcilers/circle_layer.s: src/c/reconcilers/circle_layer.c.s

.PHONY : src/c/reconcilers/circle_layer.s

# target to generate assembly for a file
src/c/reconcilers/circle_layer.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/circle_layer.c.s
.PHONY : src/c/reconcilers/circle_layer.c.s

src/c/reconcilers/image_layer.o: src/c/reconcilers/image_layer.c.o

.PHONY : src/c/reconcilers/image_layer.o

# target to build an object file
src/c/reconcilers/image_layer.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/image_layer.c.o
.PHONY : src/c/reconcilers/image_layer.c.o

src/c/reconcilers/image_layer.i: src/c/reconcilers/image_layer.c.i

.PHONY : src/c/reconcilers/image_layer.i

# target to preprocess a source file
src/c/reconcilers/image_layer.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/image_layer.c.i
.PHONY : src/c/reconcilers/image_layer.c.i

src/c/reconcilers/image_layer.s: src/c/reconcilers/image_layer.c.s

.PHONY : src/c/reconcilers/image_layer.s

# target to generate assembly for a file
src/c/reconcilers/image_layer.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/image_layer.c.s
.PHONY : src/c/reconcilers/image_layer.c.s

src/c/reconcilers/layer.o: src/c/reconcilers/layer.c.o

.PHONY : src/c/reconcilers/layer.o

# target to build an object file
src/c/reconcilers/layer.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/layer.c.o
.PHONY : src/c/reconcilers/layer.c.o

src/c/reconcilers/layer.i: src/c/reconcilers/layer.c.i

.PHONY : src/c/reconcilers/layer.i

# target to preprocess a source file
src/c/reconcilers/layer.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/layer.c.i
.PHONY : src/c/reconcilers/layer.c.i

src/c/reconcilers/layer.s: src/c/reconcilers/layer.c.s

.PHONY : src/c/reconcilers/layer.s

# target to generate assembly for a file
src/c/reconcilers/layer.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/layer.c.s
.PHONY : src/c/reconcilers/layer.c.s

src/c/reconcilers/text_layer.o: src/c/reconcilers/text_layer.c.o

.PHONY : src/c/reconcilers/text_layer.o

# target to build an object file
src/c/reconcilers/text_layer.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/text_layer.c.o
.PHONY : src/c/reconcilers/text_layer.c.o

src/c/reconcilers/text_layer.i: src/c/reconcilers/text_layer.c.i

.PHONY : src/c/reconcilers/text_layer.i

# target to preprocess a source file
src/c/reconcilers/text_layer.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/text_layer.c.i
.PHONY : src/c/reconcilers/text_layer.c.i

src/c/reconcilers/text_layer.s: src/c/reconcilers/text_layer.c.s

.PHONY : src/c/reconcilers/text_layer.s

# target to generate assembly for a file
src/c/reconcilers/text_layer.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/reconcilers/text_layer.c.s
.PHONY : src/c/reconcilers/text_layer.c.s

src/c/runtime_tests/memory.o: src/c/runtime_tests/memory.c.o

.PHONY : src/c/runtime_tests/memory.o

# target to build an object file
src/c/runtime_tests/memory.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/runtime_tests/memory.c.o
.PHONY : src/c/runtime_tests/memory.c.o

src/c/runtime_tests/memory.i: src/c/runtime_tests/memory.c.i

.PHONY : src/c/runtime_tests/memory.i

# target to preprocess a source file
src/c/runtime_tests/memory.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/runtime_tests/memory.c.i
.PHONY : src/c/runtime_tests/memory.c.i

src/c/runtime_tests/memory.s: src/c/runtime_tests/memory.c.s

.PHONY : src/c/runtime_tests/memory.s

# target to generate assembly for a file
src/c/runtime_tests/memory.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/runtime_tests/memory.c.s
.PHONY : src/c/runtime_tests/memory.c.s

src/c/utils/animation_registry.o: src/c/utils/animation_registry.c.o

.PHONY : src/c/utils/animation_registry.o

# target to build an object file
src/c/utils/animation_registry.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/animation_registry.c.o
.PHONY : src/c/utils/animation_registry.c.o

src/c/utils/animation_registry.i: src/c/utils/animation_registry.c.i

.PHONY : src/c/utils/animation_registry.i

# target to preprocess a source file
src/c/utils/animation_registry.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/animation_registry.c.i
.PHONY : src/c/utils/animation_registry.c.i

src/c/utils/animation_registry.s: src/c/utils/animation_registry.c.s

.PHONY : src/c/utils/animation_registry.s

# target to generate assembly for a file
src/c/utils/animation_registry.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/animation_registry.c.s
.PHONY : src/c/utils/animation_registry.c.s

src/c/utils/layers_registry.o: src/c/utils/layers_registry.c.o

.PHONY : src/c/utils/layers_registry.o

# target to build an object file
src/c/utils/layers_registry.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/layers_registry.c.o
.PHONY : src/c/utils/layers_registry.c.o

src/c/utils/layers_registry.i: src/c/utils/layers_registry.c.i

.PHONY : src/c/utils/layers_registry.i

# target to preprocess a source file
src/c/utils/layers_registry.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/layers_registry.c.i
.PHONY : src/c/utils/layers_registry.c.i

src/c/utils/layers_registry.s: src/c/utils/layers_registry.c.s

.PHONY : src/c/utils/layers_registry.s

# target to generate assembly for a file
src/c/utils/layers_registry.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/layers_registry.c.s
.PHONY : src/c/utils/layers_registry.c.s

src/c/utils/operations.o: src/c/utils/operations.c.o

.PHONY : src/c/utils/operations.o

# target to build an object file
src/c/utils/operations.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/operations.c.o
.PHONY : src/c/utils/operations.c.o

src/c/utils/operations.i: src/c/utils/operations.c.i

.PHONY : src/c/utils/operations.i

# target to preprocess a source file
src/c/utils/operations.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/operations.c.i
.PHONY : src/c/utils/operations.c.i

src/c/utils/operations.s: src/c/utils/operations.c.s

.PHONY : src/c/utils/operations.s

# target to generate assembly for a file
src/c/utils/operations.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/operations.c.s
.PHONY : src/c/utils/operations.c.s

src/c/utils/string.o: src/c/utils/string.c.o

.PHONY : src/c/utils/string.o

# target to build an object file
src/c/utils/string.c.o:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/string.c.o
.PHONY : src/c/utils/string.c.o

src/c/utils/string.i: src/c/utils/string.c.i

.PHONY : src/c/utils/string.i

# target to preprocess a source file
src/c/utils/string.c.i:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/string.c.i
.PHONY : src/c/utils/string.c.i

src/c/utils/string.s: src/c/utils/string.c.s

.PHONY : src/c/utils/string.s

# target to generate assembly for a file
src/c/utils/string.c.s:
	$(MAKE) -f CMakeFiles/PebbleReact.dir/build.make CMakeFiles/PebbleReact.dir/src/c/utils/string.c.s
.PHONY : src/c/utils/string.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PebbleReact"
	@echo "... src/c/reconcilers/animation.o"
	@echo "... src/c/reconcilers/animation.i"
	@echo "... src/c/reconcilers/animation.s"
	@echo "... src/c/reconcilers/arc_layer.o"
	@echo "... src/c/reconcilers/arc_layer.i"
	@echo "... src/c/reconcilers/arc_layer.s"
	@echo "... src/c/reconcilers/circle_layer.o"
	@echo "... src/c/reconcilers/circle_layer.i"
	@echo "... src/c/reconcilers/circle_layer.s"
	@echo "... src/c/reconcilers/image_layer.o"
	@echo "... src/c/reconcilers/image_layer.i"
	@echo "... src/c/reconcilers/image_layer.s"
	@echo "... src/c/reconcilers/layer.o"
	@echo "... src/c/reconcilers/layer.i"
	@echo "... src/c/reconcilers/layer.s"
	@echo "... src/c/reconcilers/text_layer.o"
	@echo "... src/c/reconcilers/text_layer.i"
	@echo "... src/c/reconcilers/text_layer.s"
	@echo "... src/c/runtime_tests/memory.o"
	@echo "... src/c/runtime_tests/memory.i"
	@echo "... src/c/runtime_tests/memory.s"
	@echo "... src/c/utils/animation_registry.o"
	@echo "... src/c/utils/animation_registry.i"
	@echo "... src/c/utils/animation_registry.s"
	@echo "... src/c/utils/layers_registry.o"
	@echo "... src/c/utils/layers_registry.i"
	@echo "... src/c/utils/layers_registry.s"
	@echo "... src/c/utils/operations.o"
	@echo "... src/c/utils/operations.i"
	@echo "... src/c/utils/operations.s"
	@echo "... src/c/utils/string.o"
	@echo "... src/c/utils/string.i"
	@echo "... src/c/utils/string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

