// Operations
#define OPERATION_APPEND_CHILD 1
#define OPERATION_COMMIT_UPDATE 2
#define OPERATION_REMOVE_CHILD 3
#define OPERATION_CLEAR_PROPS 4

// Node Types
#define NODE_TYPE_TEXT_LAYER 1
#define NODE_TYPE_IMAGE_LAYER 4
#define NODE_TYPE_ANIMATION 5
#define NODE_TYPE_LAYER 6
#define NODE_TYPE_CIRCLE_LAYER 7
#define NODE_TYPE_ARC_LAYER 8
#define NODE_TYPE_PATH_LAYER 9